Ap: 0.0001
N_Mie: 2e6
alpha_t_inside: 0
alpha_t_outside: 0
beta_r: 70
beta_t: 45
c: 3e8
eta: 1.5
f: 0.5
fov: 55
g: 0.72
gamma: 0.017
h_max: 3
h_mean: 1.5
h_min: 1
n: 120
p: 0.1
particle_size: 10e-6
radius: 0.5
reflection_coef: 0.6
sampling_time: 2.5e-10
std_h: 0.5
std_w: 0.5
t: 5e-9
t_fall: 1e-9
t_rise: 5.0e-10
w_max: 3
w_mean: 2
w_min: 0.5
wavelength: 500e-9
x: 5
y: 3
z: 3.5
