alpha_t_outside: 0
alpha_t_inside: 0
beta_t: 45
Ap: 0.0001
eta: 1.5
fov: 55
beta_r: 60
reflection_coef: 0.6
p: 0.1
g: 0.72
f: 0.5
gamma: 0.017
n: 120
N_Mie: 2e6
wavelength: 500e-9
particle_size: 10e-6
radius: 0.5
t: 5e-9
c: 3e8
t_rise: 0.5e-9
t_fall: 1e-9
sampling_time: 0.25e-9
x: 5
y: 3
z: 3.5
h_min: 1
w_min: 0.5
h_max: 3
w_max: 3
h_mean: 1.5
w_mean: 2
std_h: 0.5
std_w: 0.5
